insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (9, 4, 'IMAX SAAL 1', 1);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (17, 11, 'SAAL 6', 2);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (1, 1, 'SAAL 3', 3);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (11, 1, 'SAAL 11', 4);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (8, 5, 'SAAL 11', 5);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (11, 1, 'SAAL 11', 6);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (9, 4, 'IMAX SAAL 1', 7);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (4, 6, 'SAAL 6', 8);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (1, 10, 'SAAL 11', 9);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (16, 7, 'SAAL 11', 10);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (8, 5, 'SAAL 11', 11);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (9, 4, 'IMAX SAAL 1', 12);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (1, 10, 'SAAL 11', 13);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (1, 1, 'SAAL 3', 14);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (11, 1, 'SAAL 11', 15);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (8, 5, 'SAAL 11', 16);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (6, 6, 'SAAL 11', 17);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (14, 6, 'IMAX SAAL 1', 18);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (6, 6, 'SAAL 11', 19);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (17, 11, 'SAAL 6', 20);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (1, 10, 'SAAL 11', 21);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (16, 7, 'SAAL 11', 22);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (22, 8, 'IMAX SAAL 1', 23);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (4, 6, 'SAAL 6', 24);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (6, 6, 'SAAL 11', 25);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (3, 4, 'SAAL 6', 26);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (14, 6, 'IMAX SAAL 1', 27);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (17, 11, 'SAAL 6', 28);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (17, 11, 'SAAL 6', 29);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (3, 4, 'SAAL 6', 30);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (1, 1, 'SAAL 3', 31);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (14, 6, 'IMAX SAAL 1', 32);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (16, 7, 'SAAL 11', 33);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (6, 6, 'SAAL 11', 34);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (3, 4, 'SAAL 6', 35);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (17, 11, 'SAAL 6', 36);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (22, 8, 'IMAX SAAL 1', 37);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (6, 6, 'SAAL 11', 38);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (22, 8, 'IMAX SAAL 1', 39);
insert into reservedSeat (seatNumber, seatRow, seatLocation, reservationId) values (16, 7, 'SAAL 11', 40);