INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (1, 1, 'IMAX SAAL 1', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (5, 2, 'IMAX SAAL 1', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (7, 3, 'IMAX SAAL 1', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (9, 4, 'IMAX SAAL 1', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (12, 5, 'IMAX SAAL 1', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (14, 6, 'IMAX SAAL 1', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (16, 7, 'IMAX SAAL 1', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (22, 8, 'IMAX SAAL 1', 'PREMIUM');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (24, 9, 'IMAX SAAL 1', 'PREMIUM');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (27, 10, 'IMAX SAAL 1', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (30, 11, 'IMAX SAAL 1', 'CINEGOLD');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (1, 1, 'SAAL 3', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (13, 3, 'SAAL 3', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (3, 6, 'SAAL 3', 'PREMIUM');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (1, 8, 'SAAL 3', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (14, 6, 'SAAL 3', 'PREMIUM');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (16, 6, 'SAAL 3', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (15, 8, 'SAAL 3', 'CINEGOLD');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (8, 4, 'SAAL 3', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (19, 9, 'SAAL 3', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (1, 1, 'SAAL 6', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (11, 5, 'SAAL 6', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (3, 4, 'SAAL 6', 'PREMIUM');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (12, 1, 'SAAL 6', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (16, 6, 'SAAL 6', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (4, 6, 'SAAL 6', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (4, 1, 'SAAL 6', 'PREMIUM');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (16, 12, 'SAAL 6', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (17, 11, 'SAAL 6', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (11, 13, 'SAAL 6', 'CINEGOLD');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (10, 7, 'SAAL 6', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (11, 1, 'SAAL 11', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (3, 2, 'SAAL 11', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (13, 3, 'SAAL 11', 'PREMIUM');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (15, 3, 'SAAL 11', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (11, 4, 'SAAL 11', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (8, 5, 'SAAL 11', 'PREMIUM');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (6, 6, 'SAAL 11', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (16, 7, 'SAAL 11', 'CINEGOLD');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (1, 10, 'SAAL 11', 'BASIC');
INSERT INTO Seat (SeatNumber, RowNumber, locatedIn, category) VALUES (2, 8, 'SAAL 11', 'BASIC');
